### ISSUE TITLE
unconditional synthesis on external dataset

### ISSUE THREAD

**Issue by ecklyn** [albertfgu/diffwave-sashimi#3]
Hello,
I am working on a project aimed at generating drum loops conditioning only on global class labels (without neural vocoding on mel-spectrograms). I modified the diffwave model of this repository:
https://github.com/lmnt-com/diffwave/tree/master/src/diffwave
and I encountered the same issue of more users, that is, unconditional generation doesn't seem to work. I was wondering if the outdated S4 layer of this repository is a serious enough problem to dissuade me from even attempting to train the diffwave+sashimi model from scratch on my drum loops dataset. If that is, may I ask how long could it take for the model to reach a stable version for training on external data? Is there a problem preventing the stable v2 version of the S4 layer from working with Diffwave? I hope my question isn't too out of place. I'm excited to properly try the model once it's functional

**Comment by albertfgu** [comment]
Yes, I also originally found that the lmnt-com repo doesn't work for unconditional generation before switching to the philsyn repo.

The S4 layer of this repository is a stable version. It's up to date with something close to the most recent released version (V3). You should be able to train either Diffwave+Wavenet or Diffwave+Sashimi from scratch from the `master` branch.

You may have gotten confused by the README claiming the models are outdated, but note that that section of the README applies only to the pretrained models on the `checkpoints` branch. I made minor wording adjustments to the [README](https://github.com/albertfgu/diffwave-sashimi#pretrained-models) to try to clarify this, but let me know if it's still unclear.

**Comment by ecklyn** [comment]
Thank you a lot, I was exactly pushed to ask for clarifications after reading the README section with the warning about training from scratch. Now it's much clearer and I'm relieved to know I can rely on the model for my experiments
