### ISSUE TITLE
`hydra` package should be `hydra-core` in `requirements.txt`

### ISSUE THREAD

**Issue by verrannt** [albertfgu/diffwave-sashimi#5]
Just wanted to get it out there that the package name for Hydra in `requirements.txt` should be `hydra-core`, and not just `hydra`. At least for me, trying to `pip install hydra` throws errors on Python 3.9.5 and 3.10.4, while `hydra-core` works fine.

It also says so in the [official Hydra documentation](https://hydra.cc/docs/1.2/intro/#quick-start-guide).

**Comment by albertfgu** [comment]
Yep, thanks for the catch!
