### ISSUE TITLE
`FileExistsError` thrown in multiprocessing setting

### ISSUE THREAD

**Issue by verrannt** [albertfgu/diffwave-sashimi#8]
There are several places in the code where directories are created, and to avoid creating them several times on each process when multiple GPUs are used, `os.path.isdir` is invoked, e.g. (in [`utils.py`](https://github.com/albertfgu/diffwave-sashimi/blob/master/utils.py#L114)):
```py
if not os.path.isdir(output_directory):
    os.makedirs(output_directory)
    os.chmod(output_directory, 0o775)
```
However, this regularly creates `FileExistsError`s for me. I assume the reason for this is that since the processes are spawned simultaneously, `os.path.isdir` may return `False` on several of them, causing `os.makedirs` to be invoked several times.

A potential fix for this could be to simply replace the above three lines with:

```py
os.makedirs(output_directly, mode=0o775, exist_ok=True)
```

This fulfills the same functionality but avoids the exception being raised.

**Comment by albertfgu** [comment]
Sorry I missed this! I'm not sure why this wasn't an issue for me. Did you end up fixing it with your proposed change? If so I can make the changes, or ask you to make a small PR if it's straightforward (I'm not sure in which locations you needed to change the code).

**Comment by verrannt** [comment]
I ended up only having to change it inside the [`local_directory()`](https://github.com/albertfgu/diffwave-sashimi/blob/f02f66bc762ed88b1fe7f992e5c2cb4a554e33cb/utils.py#L114) function in `utils.py`, which is used in both `train.py` and `generate.py`. There are other places in the latter two files where the three-line code is used, but those somehow didn't throw exceptions for me. 

Also worth noting is that it's used in [`dataloaders/mel2samp.py`](https://github.com/albertfgu/diffwave-sashimi/blob/527e5eb5e65ff3bcf54f0ce1692a54e2a5c4b523/dataloaders/mel2samp.py#L144), but I didn't use that file in my fork, so I don't know whether there's an issue here, too.

**Comment by albertfgu** [comment]
The change makes sense - I just pushed a commit fixing it in those 4 files (I didn't actually test it but trust that it should work).

Your guess for why it's failing is probably right, and it probably doesn't fail in `train.py` and `generate.py` because it's called before the multi-device is activated. Still makes sense to simplify the 3-line pattern everywhere though.
